services:
  email-service:
    build:
      dockerfile: ./apps/pickles-email-service/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev pickles-email-service
    ports:
      - 3000:3000
    depends_on:
      - redis
      - rabbitmq
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    ports:
      - 4040:4040
    env_file:
      - ./apps/users/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
volumes:
  redis:
    driver: local
