services:
  api:
    build:
      dockerfile: .docker/qa-env.Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:codewithdulan@18.188.114.169:5432/pickles-email?schema=public
      - SENTRY_DSN=https://17c060aa9a93450ea076a8faec9030c4@o1274453.ingest.sentry.io/4504971668553728
      - EMAIL_HOST=smtp.sendgrid.net
      - EMAIL_USER=apikey
      - EMAIL_PASSWORD=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
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
